# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_pb2 as inventory__pb2


class InventoryServiceStub(object):
    """InventoryService - gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInventory = channel.unary_unary(
                '/inventory.InventoryService/GetInventory',
                request_serializer=inventory__pb2.GetInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryItem.FromString,
                )
        self.ListInventory = channel.unary_unary(
                '/inventory.InventoryService/ListInventory',
                request_serializer=inventory__pb2.ListInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.ListInventoryResponse.FromString,
                )
        self.CreateInventory = channel.unary_unary(
                '/inventory.InventoryService/CreateInventory',
                request_serializer=inventory__pb2.CreateInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryItem.FromString,
                )
        self.UpdateInventory = channel.unary_unary(
                '/inventory.InventoryService/UpdateInventory',
                request_serializer=inventory__pb2.UpdateInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryItem.FromString,
                )
        self.DeleteInventory = channel.unary_unary(
                '/inventory.InventoryService/DeleteInventory',
                request_serializer=inventory__pb2.DeleteInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.Empty.FromString,
                )
        self.CheckStock = channel.unary_unary(
                '/inventory.InventoryService/CheckStock',
                request_serializer=inventory__pb2.StockCheckRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockCheckResponse.FromString,
                )
        self.ReserveStock = channel.unary_unary(
                '/inventory.InventoryService/ReserveStock',
                request_serializer=inventory__pb2.StockReserveRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockReserveResponse.FromString,
                )
        self.ReleaseStock = channel.unary_unary(
                '/inventory.InventoryService/ReleaseStock',
                request_serializer=inventory__pb2.StockReserveRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockReserveResponse.FromString,
                )


class InventoryServiceServicer(object):
    """InventoryService - gRPC service definition
    """

    def GetInventory(self, request, context):
        """Get single inventory item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInventory(self, request, context):
        """List all inventory items
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInventory(self, request, context):
        """Create new inventory item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInventory(self, request, context):
        """Update inventory item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInventory(self, request, context):
        """Delete inventory item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStock(self, request, context):
        """Check stock availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """Reserve stock for order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseStock(self, request, context):
        """Release reserved stock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventory,
                    request_deserializer=inventory__pb2.GetInventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryItem.SerializeToString,
            ),
            'ListInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInventory,
                    request_deserializer=inventory__pb2.ListInventoryRequest.FromString,
                    response_serializer=inventory__pb2.ListInventoryResponse.SerializeToString,
            ),
            'CreateInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInventory,
                    request_deserializer=inventory__pb2.CreateInventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryItem.SerializeToString,
            ),
            'UpdateInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInventory,
                    request_deserializer=inventory__pb2.UpdateInventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryItem.SerializeToString,
            ),
            'DeleteInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInventory,
                    request_deserializer=inventory__pb2.DeleteInventoryRequest.FromString,
                    response_serializer=inventory__pb2.Empty.SerializeToString,
            ),
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=inventory__pb2.StockCheckRequest.FromString,
                    response_serializer=inventory__pb2.StockCheckResponse.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=inventory__pb2.StockReserveRequest.FromString,
                    response_serializer=inventory__pb2.StockReserveResponse.SerializeToString,
            ),
            'ReleaseStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseStock,
                    request_deserializer=inventory__pb2.StockReserveRequest.FromString,
                    response_serializer=inventory__pb2.StockReserveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """InventoryService - gRPC service definition
    """

    @staticmethod
    def GetInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/GetInventory',
            inventory__pb2.GetInventoryRequest.SerializeToString,
            inventory__pb2.InventoryItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/ListInventory',
            inventory__pb2.ListInventoryRequest.SerializeToString,
            inventory__pb2.ListInventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/CreateInventory',
            inventory__pb2.CreateInventoryRequest.SerializeToString,
            inventory__pb2.InventoryItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/UpdateInventory',
            inventory__pb2.UpdateInventoryRequest.SerializeToString,
            inventory__pb2.InventoryItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/DeleteInventory',
            inventory__pb2.DeleteInventoryRequest.SerializeToString,
            inventory__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/CheckStock',
            inventory__pb2.StockCheckRequest.SerializeToString,
            inventory__pb2.StockCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/ReserveStock',
            inventory__pb2.StockReserveRequest.SerializeToString,
            inventory__pb2.StockReserveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/ReleaseStock',
            inventory__pb2.StockReserveRequest.SerializeToString,
            inventory__pb2.StockReserveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
