# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """/ <summary>
    / Servicio gRPC encargado de gestionar las operaciones relacionadas con orders.
    / Permite la creación, consulta, actualización de estado y cancelación de orders.
    / </summary>
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/Orders.OrderService/CreateOrder',
                request_serializer=order__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=order__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/Orders.OrderService/GetOrderStatus',
                request_serializer=order__pb2.GetOrderStatusRequest.SerializeToString,
                response_deserializer=order__pb2.GetOrderStatusResponse.FromString,
                _registered_method=True)
        self.ChangeOrderState = channel.unary_unary(
                '/Orders.OrderService/ChangeOrderState',
                request_serializer=order__pb2.ChangeOrderStateRequest.SerializeToString,
                response_deserializer=order__pb2.ChangeOrderStateResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/Orders.OrderService/CancelOrder',
                request_serializer=order__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=order__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetUserOrders = channel.unary_unary(
                '/Orders.OrderService/GetUserOrders',
                request_serializer=order__pb2.GetUserOrdersRequest.SerializeToString,
                response_deserializer=order__pb2.GetUserOrdersResponse.FromString,
                _registered_method=True)
        self.GetAdminOrders = channel.unary_unary(
                '/Orders.OrderService/GetAdminOrders',
                request_serializer=order__pb2.GetAdminOrdersRequest.SerializeToString,
                response_deserializer=order__pb2.GetAdminOrdersResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """/ <summary>
    / Servicio gRPC encargado de gestionar las operaciones relacionadas con orders.
    / Permite la creación, consulta, actualización de estado y cancelación de orders.
    / </summary>
    """

    def CreateOrder(self, request, context):
        """/ <summary>
        / Crea una nueva orden en el sistema a partir de los datos del usuario y los productos solicitados.
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """/ <summary>
        / Obtiene el estado actual de orden a partir de su identificador.
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeOrderState(self, request, context):
        """/ <summary>
        / Cambia el estado de orden.
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """/ <summary>
        / Cancela una orden existente segun su identificador.
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserOrders(self, request, context):
        """/ <summary>
        / Obtiene todas las ordenes asociadas a un usuario, permitiendo filtros por fecha o identificadores.
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminOrders(self, request, context):
        """/ <summary>
        / Permite al administrador consultar todas las ordenes registradas con filtros opcionales.
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=order__pb2.CreateOrderRequest.FromString,
                    response_serializer=order__pb2.CreateOrderResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=order__pb2.GetOrderStatusRequest.FromString,
                    response_serializer=order__pb2.GetOrderStatusResponse.SerializeToString,
            ),
            'ChangeOrderState': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeOrderState,
                    request_deserializer=order__pb2.ChangeOrderStateRequest.FromString,
                    response_serializer=order__pb2.ChangeOrderStateResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=order__pb2.CancelOrderRequest.FromString,
                    response_serializer=order__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetUserOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOrders,
                    request_deserializer=order__pb2.GetUserOrdersRequest.FromString,
                    response_serializer=order__pb2.GetUserOrdersResponse.SerializeToString,
            ),
            'GetAdminOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminOrders,
                    request_deserializer=order__pb2.GetAdminOrdersRequest.FromString,
                    response_serializer=order__pb2.GetAdminOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Orders.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Orders.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """/ <summary>
    / Servicio gRPC encargado de gestionar las operaciones relacionadas con orders.
    / Permite la creación, consulta, actualización de estado y cancelación de orders.
    / </summary>
    """

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orders.OrderService/CreateOrder',
            order__pb2.CreateOrderRequest.SerializeToString,
            order__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orders.OrderService/GetOrderStatus',
            order__pb2.GetOrderStatusRequest.SerializeToString,
            order__pb2.GetOrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeOrderState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orders.OrderService/ChangeOrderState',
            order__pb2.ChangeOrderStateRequest.SerializeToString,
            order__pb2.ChangeOrderStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orders.OrderService/CancelOrder',
            order__pb2.CancelOrderRequest.SerializeToString,
            order__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orders.OrderService/GetUserOrders',
            order__pb2.GetUserOrdersRequest.SerializeToString,
            order__pb2.GetUserOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orders.OrderService/GetAdminOrders',
            order__pb2.GetAdminOrdersRequest.SerializeToString,
            order__pb2.GetAdminOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
